name: 'Sync Integration Templates'

on:
    workflow_dispatch:

jobs:
    sync-integration-templates:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install nango CLI
              run: |
                  npm install -g nango

            - name: Sync all templates
              run: |
                  cd integration-templates
                  for dir in $(ls -d */); do
                      integration=$(basename $dir)
                      mkdir -p /tmp/nango-temp/nango-integrations/$integration

                      cp $dir/nango.yaml /tmp/nango-temp/nango-integrations/
                      cp -r $dir/* /tmp/nango-temp/nango-integrations/$integration/

                      pushd /tmp/nango-temp/nango-integrations
                      nango compile
                      popd

                      cp -r /tmp/nango-temp/nango-integrations/dist ./$integration/dist
                      cp -r /tmp/nango-temp/nango-integrations/.nango ./$integration/.nango

                      rm -rf /tmp/nango-temp

                      aws s3 sync $integration s3://${{ secrets.AWS_BUCKET_NAME }}/integration-templates/$integration/
                  done
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
